### ISSUE TITLE
Block content in doc-level translations not always de-serializing correctly

### ISSUE THREAD

**Issue by apennell** [sanity-io/sanity-plugin-studio-smartling#12]
Thanks for the great plugin--it's made translating with Smartling much easier!

I've been working more document-level translation recently (using Sanity's document-internationalization plugin) and it's going well for the most part, but I've been having issues with some translated fields not importing and being replaced with the English. They're serializing fine and reaching Smartling, but don't make their way back into the Sanity dataset after deserialization, although I can see that the content is in the html returned to the plugin from Smartling.

It seems to mostly be happening in fields that are using block content. Here's a screenshot showing the translations that I'd previously copy-pasted from Smartling into Sanity getting overwritten after importing a translation update from Smartling:
![Screen Shot 2022-06-17 at 3 24 34 PM](https://user-images.githubusercontent.com/11039888/174409940-23d2cc75-2670-49be-ab73-a672f9477678.png)

I saved the raw json that was returned from the Smartling post. Here's one super specific part with content that didn't make it into Sanity:

```json
{
"body":"...otherStuffImNotIncluding...<div class=\"infoItems\" data-type=\"array\"><div class=\"infoListItem\" id=\"a3da741093fd\" data-type=\"object\"><span class=\"heading\">Повний спектр послуг дизайну та локалізації</span><div class=\"bodyBlock\" data-type=\"array\"><p>Талановиті фахівці нашої глобальної команди – основні учасники вашого проекту.</p></div></div>...otherStuffIDidntInclude..."
}
```

Here's a snippet from the Sanity inspector of that same `infoItem` after import. The `heading` made it in but the string in the `<p>` ("Талановиті фахівці ...") should be in the bodyBlock's `text` ("Our distributed team...").

```json
{
"category": "Про нас",
      "heading": "Що ми робимо",
      "infoItems": [
        {
          "_key": "a3da741093fd",
          "_type": "infoListItem",
          "bodyBlock": [
            {
              "_key": "fb8b65493b8d",
              "_type": "block",
              "children": [
                {
                  "_key": "595643fcec3d0",
                  "_type": "span",
                  "marks": [],
                  "text": "Our distributed team of talented experts contribute as core members for your project."
                }
              ],
              "markDefs": [],
              "style": "body1"
            }
          ],
          "heading": "Повний спектр послуг дизайну та локалізації"
        },
    ]
}
```

This issue may actual be in [sanity-naive-html-serializer](https://github.com/sanity-io/sanity-naive-html-serializer/)--apologies if I'm reporting in the wrong repo!

Please let me know if there's anything I can do to make this work correctly, either with a custom serializer or by submitting a PR.

**Comment by apennell** [comment]
I'm seeing some new and strange behavior and I don't see any changes I made to the schema that would have caused this so I don't know why it just started. I have a `hero` object of fields and they're being imported as an array of objects with a key `undefined` inside of hero:
<img width="1097" alt="Screen Shot 2022-06-27 at 1 16 07 PM" src="https://user-images.githubusercontent.com/11039888/176028990-cee8112a-f802-4e21-9f07-e8ea804a5250.png">
<img width="1112" alt="Screen Shot 2022-06-27 at 1 10 24 PM" src="https://user-images.githubusercontent.com/11039888/176029012-47ce8c8c-27bc-42dd-b25e-6b669789fd82.png">

Here's the raw json of that part:
```
"hero": {
    "bodyBlock": [
      {
        "_key": "dce7c9ad3a5c",
        "_type": "block",
        "children": [
          {
            "_key": "9d7b5583766e0",
            "_type": "span",
            "marks": [],
            "text": "Talent is everywhere; opportunities are not."
          }
        ],
        "markDefs": [],
        "style": "body1"
      }
    ],
    "callToAction": {
      "_type": "callToAction",
      "link": {
        "_type": "link",
        "blank": false,
        "internalReference": {
          "_ref": "a2512b20-fc8b-4ab7-9a1f-25e591345e8a",
          "_type": "reference"
        }
      },
      "text": "Let's work together"
    },
    "heading": "Your projects powered by our global teams.",
    "undefined": [
      [
        {
          "_key": "dce7c9ad3a5c",
          "_type": "block",
          "children": [
            {
              "_key": "cb191c9b40800",
              "_type": "span",
              "marks": [],
              "text": "Талант є всюди, а можливості — ні."
            }
          ],
          "markDefs": [],
          "style": "normal"
        }
      ],
      {
        "_key": "",
        "_type": "callToAction",
        "callToAction": {
          "link": {},
          "text": "Працюймо разом"
        }
      },
      "Ваші проекти підтримуються нашою глобальною командою."
    ]
  },
```

**Comment by cngonzalez** [comment]
Hopefully this has been resolved, but will re-open the issue if needed.
